language: ruby
sudo: false
addons:
  code_climate:
    repo_token: f5101c656b72b052e4d809276320e6aa79f94ce713e676a7b7d9dba41891cc8d
rvm:
- 2.3.1
- ruby-head
before_install:
- gem install bundle
install:
- bundle install
script:
- bundle exec rspec
