source 'https://rubygems.org'

gem 'rspec'
gem 'yard'
gem 'simplecov'
gem 'codeclimate-test-reporter'
gem 'moon-boolean',        github: 'polyfox/moon-boolean'
gem 'moon-data_model',     '>= 1.0.1', github: 'polyfox/moon-data_model'
gem 'moon-inflector',      github: 'polyfox/moon-inflector'
gem 'moon-logfmt',         github: 'polyfox/moon-logfmt'
gem 'moon-null_io',        github: 'polyfox/moon-null_io'
gem 'moon-packages',       github: 'polyfox/moon-packages'
gem 'moon-packages-proto', github: 'IceDragon200/moon-packages-proto'
gem 'moon-packages-mock',  github: 'polyfox/moon-packages-mock'
gem 'moon-prototype',      github: 'polyfox/moon-prototype'
gem 'moon-maybe_copy',     '>= 1.1.0', github: 'polyfox/moon-maybe_copy'
gem 'moon-serializable',   github: 'polyfox/moon-serializable'
