require 'scripts/entity_system/systems/actions'
require 'scripts/entity_system/systems/movement'
require 'scripts/entity_system/systems/rendering'
require 'scripts/entity_system/systems/scripting'
require 'scripts/entity_system/systems/spawning'
require 'scripts/entity_system/systems/tactics'
require 'scripts/entity_system/systems/thinks'
require 'scripts/entity_system/systems/navigation_render'
