require 'scripts/core_ext'
require 'scripts/version'
require 'scripts/core'
require 'scripts/debug/eventable'
require 'scripts/enums'
require 'scripts/models'
require 'scripts/helpers'
require 'scripts/entity_system'
require 'scripts/states'
require 'scripts/adapters'

require 'scripts/main'
