require "scripts/test/character_walk"
require "scripts/test/ui_test01"
require "scripts/test/roadmap-0001"
require "scripts/test/roadmap-0002"
require "scripts/test/roadmap-0003"
require "scripts/test/roadmap-0004"
